"""GitHub App / Actions glue.

- `verify_signature` validates the `X-Hub-Signature-256` HMAC so the webhook
  endpoint can trust a payload.
- `pr_comment_markdown` renders a static or runtime report as a PR comment.
- `post_pr_comment` posts it back (best-effort; no-op without a token).

Outbound calls are intentionally optional: the webhook still works as a
scan trigger even when no token is configured.
"""
from __future__ import annotations

import hashlib
import hmac
import logging

log = logging.getLogger("redline.integrations.github")

_SEV_EMOJI = {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "⚪"}


def verify_signature(secret: str, body: bytes, signature_header: str | None) -> bool:
    """Constant-time check of GitHub's `sha256=` HMAC header.

    With no secret configured, verification is skipped (returns True) so the
    webhook still works in trusted/internal deployments.
    """
    if not secret:
        return True
    if not signature_header or not signature_header.startswith("sha256="):
        return False
    expected = "sha256=" + hmac.new(
        secret.encode(), body, hashlib.sha256).hexdigest()
    return hmac.compare_digest(expected, signature_header)


def _summary_line(report: dict) -> str:
    s = report.get("summary", {})
    bs = s.get("by_severity", {})
    return (f"**{s.get('risk_level', 'n/a')}**  ·  "
            f"🔴 {bs.get('critical', 0)}  🟠 {bs.get('high', 0)}  "
            f"🟡 {bs.get('medium', 0)}  ⚪ {bs.get('low', 0)}")


def pr_comment_markdown(report: dict, limit: int = 20) -> str:
    """Render a Redline report (static or runtime) as Markdown."""
    if report.get("error"):
        return f"### 🛑 Redline scan failed\n\n```\n{report['error']}\n```"

    kind = report.get("kind", "runtime")
    lines = [f"### 🛡️ Redline {kind} scan", "", _summary_line(report), ""]
    findings = report.get("findings", [])
    if not findings:
        lines.append("_No findings at or above the report threshold._")
        return "\n".join(lines)

    lines += ["| Sev | Rule / Category | Location | Detail |",
              "|-----|-----------------|----------|--------|"]
    for f in findings[:limit]:
        sev = f.get("severity", "low")
        emoji = _SEV_EMOJI.get(sev, "⚪")
        rule = f.get("rule_id") or f.get("category", "—")
        loc = (f"`{f['file']}:{f['line']}`"
               if f.get("file") else f.get("verdict", "—"))
        detail = (f.get("title") or f.get("reason") or "")[:120]
        lines.append(f"| {emoji} {sev} | {rule} | {loc} | {detail} |")
    if len(findings) > limit:
        lines.append(f"\n_…and {len(findings) - limit} more._")
    lines.append("\n<sub>Generated by Redline</sub>")
    return "\n".join(lines)


def post_pr_comment(repo: str, pr_number: int, body: str,
                    token: str) -> bool:
    """POST a comment to a PR. No-op (returns False) without a token."""
    if not token:
        log.info("no GITHUB_TOKEN — skipping PR comment for %s#%s",
                 repo, pr_number)
        return False
    try:
        import httpx

        resp = httpx.post(
            f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments",
            headers={"Authorization": f"Bearer {token}",
                     "Accept": "application/vnd.github+json"},
            json={"body": body}, timeout=15,
        )
        ok = resp.status_code < 300
        if not ok:
            log.warning("PR comment failed: %s %s",
                        resp.status_code, resp.text[:200])
        return ok
    except Exception as e:  # noqa: BLE001 — never crash the webhook
        log.warning("PR comment error: %s", e)
        return False


def extract_pr_event(payload: dict) -> dict | None:
    """Pull (repo, clone_url, pr_number) from a pull_request webhook payload.

    Returns None for events we don't act on (so the webhook can 200 quietly).
    """
    if payload.get("action") not in ("opened", "synchronize", "reopened"):
        return None
    pr = payload.get("pull_request")
    repo = payload.get("repository")
    if not pr or not repo:
        return None
    return {
        "repo": repo.get("full_name", ""),
        "clone_url": repo.get("clone_url", ""),
        "pr_number": pr.get("number"),
        "head_sha": (pr.get("head") or {}).get("sha", ""),
    }
